namespace D4P.CCMS.Permissions;

using D4P.CCMS.Auth;
using D4P.CCMS.Backup;
using D4P.CCMS.Capacity;
using D4P.CCMS.Connector;
using D4P.CCMS.Connector.RestClientOAuth;
using D4P.CCMS.Customer;
using D4P.CCMS.Environment;
using D4P.CCMS.Extension;
using D4P.CCMS.Features;
using D4P.CCMS.General;
using D4P.CCMS.Operations;
using D4P.CCMS.PartnerCenter;
using D4P.CCMS.Session;
using D4P.CCMS.Setup;
using D4P.CCMS.Telemetry;
using D4P.CCMS.Tenant;

permissionset 62000 "D4P BC ADMIN"
{
    Assignable = true;
    Caption = 'D365BC Admin Center - Full Access';
    Permissions =
        tabledata "D4P AppInsights Connection" = RIMD,
        tabledata "D4P BC Admin Center Cue" = RIMD,
        tabledata "D4P BC App Registration" = RIMD,
        tabledata "D4P BC Available Update" = RIMD,
        tabledata "D4P BC Capacity Header" = RIMD,
        tabledata "D4P BC Capacity Line" = RIMD,
        tabledata "D4P BC Customer" = RIMD,
        tabledata "D4P BC Environment" = RIMD,
        tabledata "D4P BC Environment Backup" = RIMD,
        tabledata "D4P BC Environment Feature" = RIMD,
        tabledata "D4P BC Environment Operation" = RIMD,
        tabledata "D4P BC Environment Session" = RIMD,
        tabledata "D4P BC Installed App" = RIMD,
        tabledata "D4P BC Partner Center" = RIMD,
        tabledata "D4P BC Setup" = RIMD,
        tabledata "D4P BC Tenant" = RIMD,
        tabledata "D4P Entra App Registration" = RIMD,
        tabledata "D4P Entra Certificate" = RIMD,
        tabledata "D4P Entra Secret" = RIMD,
        tabledata "D4P PTE Object Range" = RIMD,
        table "D4P AppInsights Connection" = X,
        table "D4P BC Admin Center Cue" = X,
        table "D4P BC App Registration" = X,
        table "D4P BC Available Update" = X,
        table "D4P BC Capacity Header" = X,
        table "D4P BC Capacity Line" = X,
        table "D4P BC Customer" = X,
        table "D4P BC Environment" = X,
        table "D4P BC Environment Backup" = X,
        table "D4P BC Environment Feature" = X,
        table "D4P BC Environment Operation" = X,
        table "D4P BC Environment Session" = X,
        table "D4P BC Installed App" = X,
        table "D4P BC Partner Center" = X,
        table "D4P BC Setup" = X,
        table "D4P BC Tenant" = X,
        table "D4P Entra App Registration" = X,
        table "D4P Entra Certificate" = X,
        table "D4P Entra Secret" = X,
        table "D4P PTE Object Range" = X,
        report "D4P Get Installed Apps" = X,
        report "D4P Load Data" = X,
        codeunit "D4P AppInsights Client" = X,
        codeunit "D4P Auth Code Grant Flow Impl." = X,
        codeunit "D4P Auth. Code Grant Flow" = X,
        codeunit "D4P BC App Registration" = X,
        codeunit "D4P BC Backup Helper" = X,
        codeunit "D4P BC Capacity Helper" = X,
        codeunit "D4P BC Debug Helper" = X,
        codeunit "D4P BC Environment Helper" = X,
        codeunit "D4P BC Environment Mgt" = X,
        codeunit "D4P BC Features Helper" = X,
        codeunit "D4P BC Operations Helper" = X,
        codeunit "D4P BC Session Helper" = X,
        codeunit "D4P Client Credentials Flow" = X,
        codeunit "D4P ClientCredentialsFlow Impl" = X,
        codeunit "D4P Device Code Flow" = X,
        codeunit "D4P Device Code Flow Impl." = X,
        codeunit "D4P Entra Certificate Mgt" = X,
        codeunit "D4P Http Auth. OAuth2" = X,
        codeunit "D4P Http Auth. OAuth2 Impl." = X,
        codeunit "D4P Http Client Handler" = X,
        codeunit "D4P Microsoft Entra ID" = X,
        codeunit "D4P Microsoft Entra ID Impl." = X,
        codeunit "D4P OAuth Appl. Config" = X,
        codeunit "D4P OAuth Appl. Config Impl." = X,
        codeunit "D4P OAuth Certificate" = X,
        codeunit "D4P OAuth Certificate Impl." = X,
        codeunit "D4P OAuth Conf. Client Impl." = X,
        codeunit "D4P OAuth Confidential Client" = X,
        codeunit "D4P OAuth Public Client" = X,
        codeunit "D4P OAuth Public Client Impl." = X,
        codeunit "D4P OAuth Result" = X,
        codeunit "D4P OAuth Result Impl." = X,
        codeunit "D4P Redirect URI Built-in" = X,
        codeunit "D4P Redirect URI None" = X,
        codeunit "D4P Telemetry Helper" = X,
        codeunit "D4P Time Helper" = X,
        codeunit D4PBCAdminAPIClient = X,
        codeunit D4PBCAutomationAPIClient = X,
        codeunit D4PBCRestClientFactory = X,
        page "D4P AppInsights Conn Card" = X,
        page "D4P AppInsights Conn List" = X,
        page "D4P Auth. Code Grant Flow" = X,
        page "D4P BC Admin Center Cues" = X,
        page "D4P BC Admin Headline" = X,
        page "D4P BC Admin Role Center" = X,
        page "D4P BC App Registration Card" = X,
        page "D4P BC App Registration List" = X,
        page "D4P BC Capacity Card" = X,
        page "D4P BC Capacity List" = X,
        page "D4P BC Capacity Subform" = X,
        page "D4P BC Capacity Worksheet" = X,
        page "D4P BC Customer Card" = X,
        page "D4P BC Customer FactBox" = X,
        page "D4P BC Customers List" = X,
        page "D4P BC Environment Backups" = X,
        page "D4P BC Environment Card" = X,
        page "D4P BC Environment Features" = X,
        page "D4P BC Environment List" = X,
        page "D4P BC Environment Operations" = X,
        page "D4P BC Environment Sess Card" = X,
        page "D4P BC Environment Sessions" = X,
        page "D4P BC Environments FactBox" = X,
        page "D4P BC Installed App Card" = X,
        page "D4P BC Installed Apps FactBox" = X,
        page "D4P BC Installed Apps List" = X,
        page "D4P BC Partner Center List" = X,
        page "D4P BC Setup" = X,
        page "D4P BC Tenant Card" = X,
        page "D4P BC Tenant FactBox" = X,
        page "D4P BC Tenant List" = X,
        page "D4P Copy Environment Dialog" = X,
        page "D4P Device Code Authorization" = X,
        page "D4P Entra App Registr. Card" = X,
        page "D4P Entra App Registr. List" = X,
        page "D4P Entra Certificates" = X,
        page "D4P Entra Secret Subform" = X,
        page "D4P Export History Dialog" = X,
        page "D4P New Environment Dialog" = X,
        page "D4P PTE Object Ranges" = X,
        page "D4P Rename Environment Dialog" = X,
        page "D4P Tenant Migration Dialog" = X,
        page "D4P Update Selection Dialog" = X;
}